### ISSUE TITLE
using with AccountTemplates

### ISSUE THREAD

**Issue by sunstorymvp** [VeliovGroup/Meteor-iron-router-title#2]
Hi! It would be great to set AT routes titles the same way

``` coffeescript
AccountsTemplates.configureRoute 'signIn',
  path: '/users/login'
  template: 'loginPage'
  title: 'Please, log in'
```

or even like 

``` coffeescript
AccountsTemplates.configureRoute 'signIn',
  path: '/users/login'
  template: 'loginPage'
  title: -> "Hey #{@data().user.fullname}! Please, log in"
```

Now it throws `Match error`

**Comment by dr-dimitru** [comment]
@sunstorymvp It should work out of the box, could you provide full error stack trace, please?

**Comment by sunstorymvp** [comment]
I'm sorry, apparently I did not spend enough time studying the issue.
I found that AccountsTemplates.configureRoute method passes options directly to Router.map, but not all options.
https://github.com/meteor-useraccounts/core/blob/master/Guide.md#routing
https://github.com/meteor-useraccounts/core/blob/ec1434bd04a6ca930a60c0db03414ca5ec551beb/lib/core.js#L192-L199
so problem is not with your package

**Comment by dr-dimitru** [comment]
@sunstorymvp We should send pull request.
I'm ready to contribute

**Comment by dr-dimitru** [comment]
@sunstorymvp any news on your end?

**Comment by sunstorymvp** [comment]
unfortunately I do not have enough time to explore it now =/ 
I guess that the key is route configuration pattern (https://github.com/meteor-useraccounts/core/blob/ec1434bd04a6ca930a60c0db03414ca5ec551beb/lib/core.js#L192-L199), it might be more flexible.
